### ISSUE TITLE
Add .github/workflow folder

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/FluxNLPModels.jl#1]
Same as https://github.com/JuliaSmoothOptimizers/JSOTemplate.jl

**Comment by tmigot** [comment]
To have the documentation working, you will need to generate a DOCUMENTER_KEY and add it to your github package https://documenter.juliadocs.org/stable/man/hosting/#travis-ssh

**Comment by farhadrclass** [comment]
For this, do I use JSO or do I use my personal github?

**Comment by tmigot** [comment]
Use your personal Github and we will replace it by JSO later

**Comment by farhadrclass** [comment]
@tmigot can you check and see if this is correct ?

**Comment by farhadrclass** [comment]
@tmigot can you check and see if this is correct ?

**Comment by dpo** [comment]
Close this?
