### ISSUE TITLE
BenchmarkTools

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/FluxNLPModels.jl#10]
BenchmarkTools should not be a test dependency. You don't seem to use it anyways. Please remove everything that isn't a strict dependency.

**Comment by paraynaud** [comment]
@farhadrclass, here is your current Projet.toml:
```julia
[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
SolverTest = "4343dc35-3317-4c6e-8877-f0cc8502c90e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "BenchmarkTools", "Test"]
```
If the modules are not appearing in the `[targets]` section, then there is no need for them to be in the `[extra]` (ex: Quadmath ).
Also, the modules in `[deps]` are not required in `[extra]` (ex: LinearAlgebra).
If you need to have other modules during the FluxNLPModels.jl development, open a new Packages environment, where you load locally your FluxNLPModels.jl version of the code.
