### ISSUE TITLE
Add multiprecision tests

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/FluxNLPModels.jl#4]
If we do `obj(nlp, x32)` with a vector of type `Float32`, will it return a `Float32` ? Same for other precisions. This should be added to the unit tests.

**Comment by farhadrclass** [comment]
I am moving this to future, as we need to focus on moving our code to JSO

**Comment by farhadrclass** [comment]
I am adding this as part of the https://github.com/JuliaSmoothOptimizers/FluxNLPModels.jl/issues/15 
#15
